apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend # 프론트엔드 배포의 이름
  labels:
    app: frontend # 이 배포의 Pod들을 식별할 레이블
spec:
  replicas: 2 # 안정성을 위해 Pod 인스턴스를 2개로 설정 (필요에 따라 조절)
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend # 컨테이너 이름
        image: project20registry.azurecr.io/frontend:latest # ***푸시한 이미지 경로와 동일해야 합니다!***
        ports:
        - containerPort: 80 # Nginx가 노출하는 포트 (Dockerfile에서 EXPOSE 80 했던 포트)
        resources: # (선택 사항) Pod에 할당할 CPU/메모리 리소스 제한 (필수 아님, 성능 문제 시 고려)
          requests:
            cpu: "100m"  # 0.1 CPU 코어 요청
            memory: "128Mi" # 128 MiB 메모리 요청
          limits:
            cpu: "200m"  # 0.2 CPU 코어 제한
            memory: "256Mi" # 256 MiB 메모리 제한
